### ISSUE TITLE
Add support for Zola

### ISSUE THREAD

**Issue by throwaway1037** [seancdavis/ssg-build-performance-tests#22]
This project could become the [Computer Language Benchmarks Game](https://benchmarksgame-team.pages.debian.net/benchmarksgame/index.html) of static site generators.

**Comment by seancdavis** [comment]
That's the hope! 😄 

I appreciate your contributions here. I started out with a few of the more popular SSG choices, and am trying to build and maintain a platform that makes it relatively easy for maintainers of SSGs to add their own projects.

I'm working through a few issues at the moment that are getting in the way. But I'm not going to personally add any more SSGs. You're welcome to contribute a PR with Zola.
