### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by throwaway1037** [seancdavis/ssg-build-performance-tests#23]
I propose a [free software](https://wikipedia.org/wiki/free_software) license be copied into a `LICENSE.txt` file. I would personally recommend the GNU General Public License version 3 (only).

**Comment by seancdavis** [comment]
Thanks for this! Totally forgot about it. I prefer the MIT license for this type of project, at least at this time.

**Comment by throwaway1037** [comment]
Thank you.
