### ISSUE TITLE
How can we add or configure other documentation sites like Docusaurus etc... on SSG Build Performance Comparison

### ISSUE THREAD

**Issue by sachipanda** [seancdavis/ssg-build-performance-tests#36]
Thank you Sean,

It was pleasure to working  with you, I was going through the ssg-build-performance-tests repository and as mentioned on the readme file the steps were very clear and loud , I am able to set-up the SSG Build Performance Comparison chart.

I was trying to add few more documentation sites to compare(e.g  Docusaurus, Docify etc...  ), and remove few which is not required in terms of comparison, I am not able to find any steps on the configuration. Is there any way how can we achieve this ? 
Can you please guide on this how we can do this custom configuration ?

Thank You,
Sachidananda Panda

**Comment by seancdavis** [comment]
Sorry for the long delay, @sachipanda. The intention here is that you aren't running the front end in development unless there's something you want to change structurally on the page. The front end is simply a reflection of the results that are run with GitHub actions and stored in a remote database.

[This section of the README](https://github.com/seancdavis/ssg-build-performance-tests#running-front-end) mentions that there is an example results file at `src/results-example.json` that you can copy to `src/results.json` when running the front end locally. But it won't pull in your tests.

If you get [your tests running locally for your SSG(s)](https://github.com/seancdavis/ssg-build-performance-tests#running-tests), then I'll manually trigger a series of runs with the GitHub Actions, and  they will show up on the front end of the production site.

IOW focus on getting the tests to run and don't worry about the front end in development. Once you open a PR, will run the suite and if all the runs can complete, then I'll merge the code.
