### ISSUE TITLE
Use the latest version of Jekyll 

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/ssg-build-performance-tests#5]
From @DirtyF:

> I was wondering if you could test with latest jekyll master, I’be curious to see how much it performs on your benchmark 
>
> `gem "jekyll", github: "jekyll/jekyll"`
>
> We are also conducting tests with next Kramdown and Nokogiri versions responsible for most of the rendering and build time, also Ruby 3.0-pre is around the corner, but we don’t expect any significicant (< 20%) improvement from those.

**Comment by moorereason** [comment]
Additionally, it would be helpful to capture the exact version of each SSG in the results.

**Comment by seancdavis** [comment]
Like the idea, @moorereason. Moved to #9.
