### ISSUE TITLE
Add elderjs - aims to be large-site optimized

### ISSUE THREAD

**Issue by jasikpark** [seancdavis/ssg-build-performance-tests#75]
https://github.com/Elderjs/elderjs

https://nicholasreese.com/lessons-from-building-a-static-site-generator/ - when reading this i'm curious how the claims here match up against other frameworks. Elderjs seems quite interestingly, I might make a PR to add it in a bit if that's fine :)

**Comment by seancdavis** [comment]
Go for it! It's about time for me to start thinking about making the results a bit more scalable. I'll add another issue for that.
