### ISSUE TITLE
How to scale results?

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/ssg-build-performance-tests#76]
A handful of improvements I'd like to make aimed at making this more scalable:

- Make the front end more interactive — we want to have the data, but not overload the user with the data.
- Store the version of the SSG (if not already doing so) in the results
- Don't remove old entries, but don't bring them into the front end. It'd be nice to have the history, but don't necessarily need to surface it on the front end yet

**Comment by jasikpark** [comment]
It would definitely be nice to get this working, since I'm excited to see the difference between Astro today & after we've gotten our optimize hands on it :D
