### ISSUE TITLE
Make markdown generator its own library that this project consumes

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/ssg-build-performance-tests#85]
It generates a given number of files in a specific directory in a local environment. The first version will be super simple, given the options below to accommodate this project.

Requirements:

- It will only have an API and no CLI for the first version.
- Built with TypeScript.

Options:

- Number of files.
- Directory in which to store the files.
- Fields (frontmatter) should be configurable. Start with a basic set.
- Body presence/length should also be configurable.

Questions:

1. Should this live within this repo or separately?
2. Should it be published to NPM?

My gut is that I've needed this in other projects before (or at least when starting them), and there could be a benefit to having it as its own NPM package in a separate context.

**Comment by jasikpark** [comment]
The library could always be built in this monorepo & deployed to npm - Astro uses https://github.com/changesets/changesets + their deploy github action for easy monorepo npm deploys
