### ISSUE TITLE
Netlify builds should be triggered from successful runs

### ISSUE THREAD

**Issue by seancdavis** [seancdavis/ssg-build-performance-tests#92]
There's no reason to run a Netlify build unless the production data has changed. Ideally, the action runs, results are logged, and the last step in the action is to kick off a Netlify build for the website.

I'm not sure if this will require the website code to be on a different branch or not. Hoping it can run against main, but not build automatically on new pushes to main.

**Comment by jasikpark** [comment]
I'm pretty sure you can set a config of which folders to ignore changes in for Netlify + you can definitely set something like [netlify-no-build] or something on commits as well
